# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
