# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveroom',
            name='file_path',
            field=models.CharField(default='tempDIR/', max_length=50),
        ),
    ]
