# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 03:05
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170805_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=backend.models.gen_user_nickname, max_length=30),
        ),
    ]
