# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 03:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170805_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
