# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170803_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveroom',
            name='file_path',
            field=models.CharField(default='./tempDIR/', max_length=50),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='thumbnail_path',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to='thumb/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='avatar/'),
        ),
    ]
