# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:06
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170807_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='frontend/static/users/default.jpg', upload_to=backend.models.get_user_path),
        ),
    ]
