# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:12
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170807_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroom',
            name='is_silence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='frontend/static/users/avatar.jpg', upload_to=backend.models.get_user_path),
        ),
    ]
