# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20170808_1012'),
        ('backend', '0006_auto_20170806_1615'),
    ]

    operations = [
    ]
